language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - rapidjson-dev
            - libfreeimage3
            - libfreeimage-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - LINKER_FLAGS=""
before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS=${LINKER_FLAGS} .
  - cmake --build . -- VERBOSE=1